### ISSUE TITLE
Crash on ubuntu 20.04

### ISSUE THREAD

**Issue by fredericgermain** [Dynamsoft/Dynamic-Web-TWAIN#11]
sudo dpkg -i ../../DynamsoftServiceSetup.deb

systemctl status dynamsoft
● dynamsoft.service - Dynamsoft Service
     Loaded: loaded (/lib/systemd/system/dynamsoft.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2021-09-13 10:08:50 CEST; 22s ago
   Main PID: 105293 (DynamsoftServic)
      Tasks: 11 (limit: 9118)
     Memory: 4.2M
     CGroup: /system.slice/dynamsoft.service
             ├─105293 /bin/sh /opt/dynamsoft/DynamsoftService/DynamsoftServiceMgr
             ├─105349 /opt/dynamsoft/DynamsoftService/DynamsoftService
             ├─105369 /opt/dynamsoft/DynamsoftService/DynamsoftScanning proxy
             ├─106465 /opt/dynamsoft/DynamsoftService/DynamsoftScanning enumSource
             └─106478 sleep 2s

sept. 13 10:09:05 thor DynamsoftServiceMgr[105293]: /opt/dynamsoft/DynamsoftService/DynamsoftServiceMgr: line 59: 106075 Segmentation fault      (core dumped) /opt/dynamsoft/DynamsoftService/DynamsoftSc>
sept. 13 10:09:05 thor DynamsoftServiceMgr[106190]: xhost:  unable to open display ""
sept. 13 10:09:07 thor DynamsoftServiceMgr[105293]: /opt/dynamsoft/DynamsoftService/DynamsoftServiceMgr: line 59: 106186 Segmentation fault      (core dumped) /opt/dynamsoft/DynamsoftService/DynamsoftSc>
sept. 13 10:09:07 thor DynamsoftServiceMgr[106259]: xhost:  unable to open display ""
sept. 13 10:09:09 thor DynamsoftServiceMgr[105293]: /opt/dynamsoft/DynamsoftService/DynamsoftServiceMgr: line 59: 106255 Segmentation fault      (core dumped) /opt/dynamsoft/DynamsoftService/DynamsoftSc>
sept. 13 10:09:09 thor DynamsoftServiceMgr[106330]: xhost:  unable to open display ""
sept. 13 10:09:11 thor DynamsoftServiceMgr[105293]: /opt/dynamsoft/DynamsoftService/DynamsoftServiceMgr: line 59: 106325 Segmentation fault      (core dumped) /opt/dynamsoft/DynamsoftService/DynamsoftSc>
sept. 13 10:09:11 thor DynamsoftServiceMgr[106397]: xhost:  unable to open display ""
sept. 13 10:09:13 thor DynamsoftServiceMgr[105293]: /opt/dynamsoft/DynamsoftService/DynamsoftServiceMgr: line 59: 106390 Segmentation fault      (core dumped) /opt/dynamsoft/DynamsoftService/DynamsoftSc>
sept. 13 10:09:13 thor DynamsoftServiceMgr[106469]: xhost:  unable to open display ""

**Comment by rebeccakak** [comment]
Please send /var/log/syslog to support@dynamsoft.com. By the way, may I know your email address?

**Comment by rebeccakak** [comment]
Are you using the [latest version V17.1.1](https://www.dynamsoft.com/web-twain/downloads/1000001-confirmation/)? If not, please try V17.1.1 and see if it works.
