### ISSUE TITLE
extract image alone

### ISSUE THREAD

**Issue by mahmooudali7** [Dynamsoft/Dynamic-Web-TWAIN#12]
Dears ,
i'm using Dynamsoft with angular 5 and when i try to drag pdf file , i got images in seperated pages not in the pdf page 

this form library documentaion :- When loading in a PDF file, DWT tries to extract images from that file, which is why the SDK can handle image-based PDF documents by default

how i can change it ?

![image](https://user-images.githubusercontent.com/10969254/141793568-a6d58480-9261-4269-88ed-ac61bdf32875.png)

**Comment by falcon-dynamsoft** [comment]
@mahmooudali7 , you can change it with [https://www.dynamsoft.com/web-twain/docs/info/api/Addon_PDF.html?ver=latest#setconvertmode](url), thanks
