### ISSUE TITLE
Container interface WebTwainId prop is required, but should be optional

### ISSUE THREAD

**Issue by acarroll-trend** [Dynamsoft/Dynamic-Web-TWAIN#14]
The `Container` interface is typed inconsistently, and incorrectly.

In the [distributed code](https://github.com/Dynamsoft/Dynamic-Web-TWAIN/blob/master/dist/types/Dynamsoft.d.ts#L499) it is typed as

```typescript
export interface Container {
    WebTwainId: string;
    ContainerId?: string;
    Width?: string | number;
    Height?: string | number;
    bNoUI?: boolean;
    bLocalService?: boolean;
}
```
which is incorrect, because `WebTwainId` is not required--only one of `WebTwainId` or `ContainerId` is required.
<hr/>

In the [API Reference](https://www.dynamsoft.com/web-twain/docs/info/api/Dynamsoft_WebTwainEnv.html?ver=latest#containers) it is described as

```typescript
interface Container {
    WebTwainId: string, // Id of the WebTwain instance
    ContainerId?: string, // Id of the element
    Width?: string | number, // Width of the element
    Height?: string | number // Height of the element
}
```

which is pretty consistent with the actual type, minus the additional boolean properties.
<hr/>

In [Features > Initialize](https://www.dynamsoft.com/web-twain/docs/indepth/features/initialize.html?ver=latest#-dynamsoftdwtload-) it is described as 

```typescript
interface Container {
    WebTwainId?: string;
    ContainerId?: string;
    Width?: string | number;
    Height?: string | number;
}
```
 with the supporting documentation that seems to be correct based on observed functionality.

> `WebTwainId` and `ContainerId` are both optional but one must exist as the identifier for that `WebTwain` instance.
<hr/>

I would like to request that `WebTwainId` is updated to be optional in the Container interface. Otherwise, we are stuck with a TypeScript error, or forced to decorate the code with `// @ts-expect-error`.

**Comment by Grace-Dynamsoft** [comment]
We would like to fix this issue in two days, thanks for your submit!
