### ISSUE TITLE
Undocumented breaking change introduced between v17.0.2 and v17.1.0

### ISSUE THREAD

**Issue by acarroll-trend** [Dynamsoft/Dynamic-Web-TWAIN#15]
Between v17.0.2 and v17.1.0, the default `Containers` were dropped from the configuration section of [dynamsoft.webtwain.min.js](https://github.com/Dynamsoft/Dynamic-Web-TWAIN/blob/master/dist/dynamsoft.webtwain.min.js).

```diff
/**
 * Basic Configuration (config.js with differences)
 */
Dynamsoft.DWT.AutoLoad = false;
-Dynamsoft.DWT.Containers = [{ ContainerId: 'dwtcontrolContainer', Width: 270, Height: 350 }];
Dynamsoft.DWT.IfAddMD5InUploadHeader = false;
Dynamsoft.DWT.IfConfineMaskWithinTheViewer = false;
```

As a result calls to [Dynamsoft.DWT.Load()](https://www.dynamsoft.com/web-twain/docs/info/api/Dynamsoft_WebTwainEnv.html?ver=latest#load) would do nothing. There were no error messages, or indicators as to where the problem may lie. The [documentation](https://www.dynamsoft.com/web-twain/docs/indepth/features/initialize.html?ver=latest#q-how-can-i-customize-the-instances) seems to indicate that this is still set in the configuration file.
<hr/>

I'd like to request that you add a **Breaking Changes** section to the [v17.1.0 release notes](https://www.dynamsoft.com/web-twain/docs/info/schedule/stable.html?ver=latest#171-06152021) and modify the [Q&A in Features > Initialize](https://www.dynamsoft.com/web-twain/docs/indepth/features/initialize.html?ver=latest#q-how-can-i-customize-the-instances). This issue took several days to track down and resolve, and I'd like others to avoid the same fate.

**Comment by Grace-Dynamsoft** [comment]
Yes, it was removed on last release, aimed to fix a bug. You can add the following line under Dynamsoft.DWT.ProductKey to make Load function take effect.
Dynamsoft.DWT.Containers = [{ ContainerId: 'dwtcontrolContainer', Width: 270, Height: 350 }];
