### ISSUE TITLE
OnWebTwainPreExecute & OnWebTwainPostExecute typed incorrectly

### ISSUE THREAD

**Issue by acarroll-trend** [Dynamsoft/Dynamic-Web-TWAIN#16]
[OnWebTwainPostExecute](https://github.com/Dynamsoft/Dynamic-Web-TWAIN/blob/master/dist/types/Dynamsoft.d.ts#L340) and  [OnWebTwainPreExecute](https://github.com/Dynamsoft/Dynamic-Web-TWAIN/blob/master/dist/types/Dynamsoft.d.ts#L344)are typed incorrectly.

```typescript
OnWebTwainPostExecute: () => {};
OnWebTwainPreExecute: () => {};
```

The return type of these functions is the empty type, but should be void since they do not return anything.

```typescript
OnWebTwainPostExecute: () => void;
OnWebTwainPreExecute: () => void;
```

**Comment by Ellie-dynamsoft** [comment]
It has been updated.
