### ISSUE TITLE
DynamsoftViewer on & off functions are incorrectly typed

### ISSUE THREAD

**Issue by acarroll-trend** [Dynamsoft/Dynamic-Web-TWAIN#17]
DynamsoftViewer [on](https://github.com/Dynamsoft/Dynamic-Web-TWAIN/blob/master/dist/types/WebTwain.Viewer.d.ts#L332) & [off](https://github.com/Dynamsoft/Dynamic-Web-TWAIN/blob/master/dist/types/WebTwain.Viewer.d.ts#L339) functions are incorrectly typed as

```typescript
on(name: string, callback: (event?: any, event1?: any, event2?: any) => void): void;
off(eventName: string, callback?: () => void): void;
```

You will receive a TS error when removing a specific callback for an event. This could be more generically typed as

```typescript
on(name: string, callback: (...arg: any[]) => void): void;
off(eventName: string, callback?: (...arg: any[]) => void): void;
```

Ideally, we would have an exact typing with conditional types

```typescript
type EventName =
    | 'pageRendered'
    | 'resize'
    // etc...

export type PageRenderedCallback = (index: number) => void
export type ResizeCallback = (width: number, height: number) => void

type EventCallback<T extends EventName> =
    T extends 'pageRendered' ? PageRenderedCallback :
    T extends 'resize' ? ResizeCallback :
    // etc...
    never

on<T extends EventName>(eventName: T, callback: EventCallback<T>): void;
off<T extends EventName>(eventName: T, callback?: EventCallback<T>): void;
```

The benefit here is a huge savings in time with no need to consult documentation, autocompletion, and lower likelihood to introduce bugs.

**Comment by Ellie-dynamsoft** [comment]
Thank you for the advice. Now, Viewer  on & off can also be typed as

on(name: string, callback: (...arg: any[]) => void): void;
off(eventName: string, callback?: (...arg: any[]) => void): void;

However, using the exact typing with conditional types is a bit complicated for us to modify, so we will not modify it for now. Anyway, thanks for the suggestion.
