### ISSUE TITLE
WebTwainUtil UnregisterEvent function is typed incorrectly

### ISSUE THREAD

**Issue by acarroll-trend** [Dynamsoft/Dynamic-Web-TWAIN#18]
WebTwainUtil [UnregisterEvent](https://github.com/Dynamsoft/Dynamic-Web-TWAIN/blob/master/dist/types/WebTwain.Util.d.ts#L73) function is incorrectly typed as

```typescript
UnregisterEvent(name: string, callback: () => void): boolean;
```

You will receive a TS error when removing a specific callback for an event. This could be more generically typed as

```typescript
UnregisterEvent(name: string, callback: (...arg: any[]) => void): boolean;
```

Ideally, we would have an exact typing with conditional types. (See the example in #17).

**Comment by Ellie-dynamsoft** [comment]
It has been updated.
