### ISSUE TITLE
IfDuplexEnabled property nor working in version 17.2.1

### ISSUE THREAD

**Issue by rocassis** [Dynamsoft/Dynamic-Web-TWAIN#21]
The property IfDuplexEnabled is not working for DWT 17.2.1 with Twain scanner of brand Panini (tested with Panini VisionX). On changelog was informed a bugfix did make not work for some scanners. This wiil be fixed or will be as is?

**Comment by falcon-dynamsoft** [comment]
@rocassis the property IfDuplexEnabled bug fixed is only for mac ICA scanner, not for twain scanner. Your twain scanner may not support IfDuplexEnabled, you can contact dynamsoft support (support@dynamsoft.com), thanks.
