### ISSUE TITLE
WebTwain Viewer fitWindow function is typed and documented incorrectly

### ISSUE THREAD

**Issue by acarroll-trend** [Dynamsoft/Dynamic-Web-TWAIN#22]
WebTwainViewer [fitWindow](https://github.com/Dynamsoft/Dynamic-Web-TWAIN/blob/master/dist/types/WebTwain.Util.d.ts#L73) function is incorrectly typed as

```typescript
/**
 * [Scope] Main viewer
 * [Description] Fit the image to the window
 * @param type Specify a type to fit. (width, height, both)
 */
fitWindow(type: string): void;
```

A better typing would be

```typescript
fitWindow(type?: 'height' | 'width'): void;
```

The JSDoc for the type is misleading, because `both` is not a valid value. That functionality is the default, if no type is provided. If you want the default functionality, then you will receive a TypeScript error. Documentation matching the [fitWindow API Reference](https://www.dynamsoft.com/web-twain/docs/info/api/WebTwain_Viewer.html?ver=latest&&matchVer=true&&cVer=true#fitwindow) would be more helpful.

**Comment by Ellie-dynamsoft** [comment]
Thank you for the advice. It has been updated.
