### ISSUE TITLE
Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.

### ISSUE THREAD

**Issue by lyubomirr** [Dynamsoft/Dynamic-Web-TWAIN#23]
Hi,
I've started to integrate your library in an Angular project, but the units tests which test the DWT component and all the others that use it fail with the following error:
Error: "Zone.js has detected that ZoneAwarePromise (window|global).Promise has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)"

I'm using Jest framework for the tests.  Do you have an idea what might cause this and how can be fixed?
Thanks in advance!

**Comment by lunaaaw** [comment]
Please try:

1) Refer to our angular sample, there is no problem with these samples.

https://github.com/Dynamsoft/web-twain-angular-cli-application

https://github.com/Dynamsoft/web-twain-angular-advanced

2) Before import 'zone.js/dist/zone' in polyfill.ts, add:
import 'core-js/es/promise'

3) Update zone.js to 0.11.5
Starting with Zone.js v0.11.1+ the import changes to:
import 'zone.js';

**Comment by jarodsmk** [comment]
I'm also getting this error, the above suggestions above didn't resolve it. @lyubomirr did you ever come right?

Also running Angular + Jest here, the test fails specifically on the component using `dwt`

**Comment by lunaaaw** [comment]
May I know which version of Angular you are using?

**Comment by jarodsmk** [comment]
@lunaaaw sure :) Here's what I'm currently targeting:

"@angular/core": "~13.3.2"
"jest": "^27.5.1"

**Comment by jarodsmk** [comment]
@lunaaaw - if it helps, here's a minimal reproduction of the issue. I'm yet to find a work around other than ignoring the failing tests

https://github.com/jarodsmk/dwt-angular-jest

I've included an explanation of the issue in the README

**Comment by lyubomirr** [comment]
@jarodsmk The only fix I came up with is to mock the whole dwt library in the test setup - `jest.mock('dwt', () => {})`. But as I have multiple libraries and apps I need to duplicate this everywhere that directly or transitively includes the library...

**Comment by lyubomirr** [comment]
@jarodsmk Did you find some work around different than mine?

**Comment by lunaaaw** [comment]
We will fix this issue in the next version (2022Q4). Please stay tuned.

**Comment by jarodsmk** [comment]
Cheers, thanks for the update @lunaaaw 💯

**Comment by jarodsmk** [comment]
> @jarodsmk Did you find some work around different than mine?

Sorry for missing your reply, I've simply ignored the integration test we have at the moment 🤷‍♂️ Tested it manually & checked that it works which is fine for the mean time
