### ISSUE TITLE
Close icon not visible anymore when dynamsoft service isn't installed

### ISSUE THREAD

**Issue by bokisha** [Dynamsoft/Dynamic-Web-TWAIN#24]
In previous versions, when you initialize dynamsoft code, and user didn't had Dynamsoft Service installed, he could choose whether to install it or just cancel operation by clicking on close icon. 
![image](https://user-images.githubusercontent.com/10226448/170775317-406e4bfb-d22c-44f4-b41d-2e88e191be1c.png)

Since Version 17.2.0 that is not possible anymore. Is there plan to bring it back?

I am using it inside angular v12 application alongside type definitions that comes along with package.

**Comment by Ellie-dynamsoft** [comment]
We will bring it back on version17.3. If you need it you can update to version17.3. Thanks.
