### ISSUE TITLE
How to run `dwt` on CI environment for testing using jsdom/happy-dom

### ISSUE THREAD

**Issue by pikax** [Dynamsoft/Dynamic-Web-TWAIN#25]
We need to write unit tests for the integration with `dwt` and we are failing to do so, because the library seems not to start correct or even throws some odd errors.

# Goal 

My goal is to be able to test/run dwt on nodejs with jsdom/happy-dom. 

# Issues 

DWT does not behave the same as when it's running on a browser, no documentation on how to do it.

# What I've done so far

I've contacted Dynamsoft support, but got into a communication issue because I've received this answers:
> Do you think it works for you to stop the service through Task Manager to simulate this status instead of uninstalling and reinstalling the service? I always use this method. And our testing team said, you can use a package capture tool likes charles to mock dwt http requests

> I just checked with our testing team. During their testing, the service part is the actual test, there is no mock behavior. So I think we are unable to assist you. Sorry about that.

# Repo

Repo is attached as zip (also provided to the support) and is a simple vue/vite/vitest sample. 

```ts
  // actual expected mock
  test("should call VersionInfo", async () => {
    // only init dwt on this test
    const App = await import("./App.vue");

    const attachTo = document.createElement("div");
    document.body.appendChild(attachTo);

    const wrapper = mount(App.default, {
      attachTo,
    });

    // await an arbitrary 20s 
    await new Promise((res) => setTimeout(res, 20000));

    expect(XMLHttpRequestFn).toHaveBeenCalled();
    // This should have been called if dwt was correctly initialised!
    expect(sendFn).toHaveBeenCalled(); // fails here because `XMLHttpRequestFn.send` is not called and it should
  }, 30000);
```

[dwt-vitest-error.zip](https://github.com/Dynamsoft/Dynamic-Web-TWAIN/files/8898743/dwt-vitest-error.zip)

**Comment by falcon-dynamsoft** [comment]
Sorry, DWT does not do compatibility check and testing for Node.js.

**Comment by pikax** [comment]
@falconmoon is there a official mock library I can use or a way for me to do some mock on some functionality that does not work on nodejs?

Is quite surprising and disappointing that there's no support for unit-testing at all.

**Comment by lunaaaw** [comment]
We will try to support jsdom in the next version (2022Q4). Please stay tuned.

**Comment by ugurk** [comment]
Hi @lunaaaw, I just checked the changelog and couldn't see any note about this. Is it supported now? if not, any plans?

**Comment by lunaaaw** [comment]
Hello @ugurk, sorry, we still don't support it. Since DWT strongly depends on the browser environment, so the environment cannot initialize DWT in nodejs. When testing DWT-related functions, for the framework projects, it is recommended to test through E2E, such as Puppeteer.
