### ISSUE TITLE
WebTwain installer downloads .deb package on windows

### ISSUE THREAD

**Issue by basz** [Dynamsoft/Dynamic-Web-TWAIN#26]
On windows (11) in parallels (on MacOS) I get to download the webtwain installer as a .deb package. This is probably becuase I am on an M1 chipset, so Windows is also the ARM version.

This is whilst using dwt v7.3.0

![image](https://user-images.githubusercontent.com/143068/184114560-a40af8ab-623f-42f0-82ef-d105c801e8c6.png)

**Comment by lincoln2018** [comment]
dwt v17.3.1 fixed

**Comment by basz** [comment]
thanks!
