### ISSUE TITLE
HTML5 Edition basic API as npm package

### ISSUE THREAD

**Issue by devopsmariocom** [Dynamsoft/Dynamic-Web-TWAIN#3]
It would be nice to have really small and simple library for calling client installed scan service, then current overbloated solution with all ui options, as currently if will start using your software our customers all around the world with bad internet connection will need to download 635 KB of code just for few lines which will get scanning done thru few http requests. Not to mention that integrating current solution into our application is near to impossible.

Also it would be nice to have it versioned with `package.json` file as other libraries these days.

I would rather create such library myself then using current solution as it seems that all one has to do is to call http endpoint in defined sequence, but I'm not sure how much often do you change service API and bit scare with supporting multiple service versions.

What do you think?

**Comment by yushulx** [comment]
Thanks for your good suggestions. We will consider to separate APIs in the future. Now if you want to download more quickly, you can activate gzip on your server-side. The size of the resources will be compressed - about 160K.

**Comment by devopsmariocom** [comment]
Thanks for quick answer, I know about compression, it's pretty much standard these days, but still we are really counting every byte for page load on not really good internet connection. Also there is still issue with integrating library in current state as it's not using any kind of module system and it's poisoning global namespace which is kind of blocking us from using your product, so please let me know if you will do any progress.

Thanks!

**Comment by yushulx** [comment]
Alright. Would you like to leave your email? Or, you can contact support@dynamsoft.com to get more information about Dynamic Web TWAIN.

**Comment by devopsmariocom** [comment]
it's mario@vejlupek.cz so please let me know if you can do anything with current client side library, as I have scrolled thru code of `dynamsoft.webtwain.initiate.js` it seems to that it should be possible separate part around `AcquireImage` from KISSY UI framework, but of course I'm looking at uglified code so it's hard to tell :), anyway it would be awesome if you could e.g. release plain code and we could participate on separation of API part from the rest and create proper npm package from it.

Thanks!

**Comment by yushulx** [comment]
@elmariofredo you can now install Dynamic Web TWAIN via `npm install dwt`.

**Comment by devopsmariocom** [comment]
main idea behind this ticket was to get basic not uglified library without other dependencies like KISSY UI framework, this was not fulfilled but thanks for your 11 months effort anyway.
