### ISSUE TITLE
WebTwain.CurrentSourceName is sometimes undefined

### ISSUE THREAD

**Issue by wildseansy** [Dynamsoft/Dynamic-Web-TWAIN#30]
Currently `CurrentSourceName` is always guaranteed to be defined on the `WebTwain` object.  However, we're finding that this is not always the case at runtime.

We're calling `WebTwain.CurrentSourceName.toLowerCase()` and sometimes `CurrentSourceName` is undefined at runtime.  Please reflect the typing so this is caught at compile time.

#### WebTwain.Acquire.d.ts
```typescript

    /**
     * Return the device name of current source.
     */
    readonly CurrentSourceName: string;
```

Version where this happened: `v17.2.5`. However, in `v18.1.0`, the `WebTwain.Acquire.d.ts` file still shows `CurrentSourceName` as not optional.

**Comment by ztyyLV** [comment]
Hi Wildseansy,

Would you mind sharing your sample code with us? We haven't reproduced the issue on our side yet. Please note, `CurrentSourceName` should always be used after `OpenSource()`.
