### ISSUE TITLE
How to develop this locally in angular

### ISSUE THREAD

**Issue by satyamcoderknight** [Dynamsoft/Dynamic-Web-TWAIN#32]
Currently If I am serving it its not working in local environment on localhost:4200. Its giving following error.
![image](https://github.com/Dynamsoft/Dynamic-Web-TWAIN/assets/98893250/fb7af17a-6767-435b-ab01-5e6be490da13)

**Comment by Ellie-dynamsoft** [comment]
We need more specific info since several possibilities exist to your question. You are welcome to contact our support online(https://www.dynamsoft.com/company/customer-service/#contact)
