### ISSUE TITLE
createImageEditor, localization problems

### ISSUE THREAD

**Issue by davidpoza** [Dynamsoft/Dynamic-Web-TWAIN#33]
Hi there!
We are using your product in our project, specifically dwt v18.2, and we are having problems with the **createImageEditor**() method. When we try to change the localized strings in the **"Select Source" modal** (**key dialogText.selectSource**), the literals aren't displayed, only the defaults are, despite of having the rest of the dialogs with the correct translation applied.

Maybe we're commiting some error, could you help us with this?.
Thanks a lot

We are following this example (v18.2): https://www.dynamsoft.com/web-twain/docs/info/api/WebTwain_Viewer.html#createimageeditor

```
// Customize the editor
var editorSettings = {
  element: document.getElementById("imageEditor"),
  width: 600,
  height: 400,
  border: "1px solid rgb(204, 204, 204)",
  topMenuBorder: "",
  innerBorder: "",
  background: "rgb(255, 255, 255)",
  promptToSaveChange: true,
  buttons: {
    titles: {
      //...
    },
    visibility: {
      //...
    },
  },
  dialogText: {
    dlgRotateAnyAngle: [
      //...
    ],
    dlgChangeImageSize: [
      //...
    ],
    saveChangedImage: [
      //...
    ],
    selectSource: [
      "Selecciona fuente:",
      "Seleccionar",
      "Cancelar",
      "No hay ninguna fuente disponible",
    ],
  },
  workMode:Dynamsoft.DWT.EnumDWT_WorkMode.balance,
};
//Create the editor 
var imageEditor = DWObject.Viewer.createImageEditor(editorSettings);
imageEditor.show();
```

**Comment by Ellie-dynamsoft** [comment]
This is a bug. You can solve it in this way before the DWT is initialized.


        Dynamsoft.DWT.AutoLoad=false;
        Dynamsoft.DWT.RegisterEvent('OnWebTwainReady', () => {
            DWObject=Dynamsoft.DWT.GetWebTwain(containerId)
        });
        
        Dynamsoft.DWT.CustomizableDisplayInfo={
            dialogText: {
                selectSource: ["Selecciona fuente:",
                    "Seleccionar",
                    "Cancelar",
                    "No hay ninguna fuente disponible",
                ]
            }
        }
        Dynamsoft.DWT.ProductKey = '';
        Dynamsoft.DWT.ResourcesPath = "/dwt-resources";
        Dynamsoft.DWT.Containers = [{
            WebTwainId: 'dwtObject',
            ContainerId: containerId,
            Width: '300px',
            Height: '400px'
        }];

        Dynamsoft.DWT.Load();

**Comment by davidpoza** [comment]
Thanks, we tested it and it's working fine now!

**Comment by Ellie-dynamsoft** [comment]
DWT 18.4 has fixed the bug you mentioned before, then you can use the code snippet below in 18.4 now. You can consider to upgrade to version 18.4. Thank you for your patience.

```
// Customize the editor
var editorSettings = {
  element: document.getElementById("imageEditor"),
  width: 600,
  height: 400,
  border: "1px solid rgb(204, 204, 204)",
  topMenuBorder: "",
  innerBorder: "",
  background: "rgb(255, 255, 255)",
  promptToSaveChange: true,
  buttons: {
    titles: {
      //...
    },
    visibility: {
      //...
    },
  },
  dialogText: {
    dlgRotateAnyAngle: [
      //...
    ],
    dlgChangeImageSize: [
      //...
    ],
    saveChangedImage: [
      //...
    ],
    selectSource: [
      "Selecciona fuente:",
      "Seleccionar",
      "Cancelar",
      "No hay ninguna fuente disponible",
    ],
  },
  workMode:Dynamsoft.DWT.EnumDWT_WorkMode.balance,
};
//Create the editor 
var imageEditor = DWObject.Viewer.createImageEditor(editorSettings);
imageEditor.show();
```
