### ISSUE TITLE
Loading document performance

### ISSUE THREAD

**Issue by davidpoza** [Dynamsoft/Dynamic-Web-TWAIN#34]
Hi,
we are experiencing a very low performance when we load pdf documents with quite a lot of pages, for example 140 pages.
It takes 10 minutes or more to load the document. Interestingly, a pdf with 50 pages takes only one minute. time seems not to be linear.
Note that we are using the method LoadImageFromBinary.

Any explanation, any suggestion for improving UX?

Thanks in advance

**Comment by falcon-dynamsoft** [comment]
DWT support local cache, please see the [details](https://www.dynamsoft.com/web-twain/docs/info/api/WebTwain_Buffer.html#buffermemorylimit), you can adjust BufferMemoryLimit to a suitable value.
