### ISSUE TITLE
Meteor JS Integration

### ISSUE THREAD

**Issue by raza2022** [Dynamsoft/Dynamic-Web-TWAIN#37]
I want to integrate it for a client project written in Meteor + Blaze, I tried the Demo code and integrated it into the full app but it doesn't work on the Customer's Mac machine, so my question is do you have a working Demo for Meteor JS (sample online)

As per my understanding, the Blaze is just purely ( HTML + Javascript Reactive Template ) so anything that works on HTML + JS should work with Meteor Blaze too, correct me if I am wrong here

here is the minimal deployed version which works fine on Windows but can find the scanner (sources) on Mac
https://dynamsoft-demo-1.meteorapp.com/

after more digging I see there is a web socket call that failed after the code initialized you can check logs on the same page as the demo  but I don't see any other clue so any help will be greatly appreciated

**Comment by raza2022** [comment]
@Ellie-dynamsoft @yushulx can you have a look at this Meteor issue or have some clues about the right path here is the demo code and deployed version of just skeleton if you wanna reproduce it though the deployed demos will cold start as it's galaxy-free dynos
Demo 1: 
Code: https://github.com/raza2022/dynamsoft-demo-1
Preview: https://dynamsoft-demo-1.meteorapp.com/

Demo 2: 
Code: https://github.com/raza2022/dynamsoft-demo-2
Preview: https://dynamsoft-demo-2.meteorapp.com/

**Comment by Ellie-dynamsoft** [comment]
The demo you deployed (https://gui3.universalcharts.com/scan-document) works fine on my Mac. The sources are all listed. I would like to ask, have you installed the TWAIN scanning driver on your Mac?

```javascript
dwtObject.GetDevicesAsync(Dynamsoft.DWT.EnumDWT_DeviceType.TWAINSCANNER | Dynamsoft.DWT.EnumDWT_DeviceType.TWAINX64SCANNER | Dynamsoft.DWT.EnumDWT_DeviceType.ESCLSCANNER)
```
Looking at your code, the sources you get are TWAIN, TWAINX64, and ESCL, but for Mac, it's better to include ICA as well: Dynamsoft.DWT.EnumDWT_DeviceType.ICASCANNER.

Also, we noticed a WebSocket error, but this error is not from Dynamic-Web-TWAIN; it's your own WebSocket connection to 'wss://gui3.universalcharts.com/sockjs/663/av1fxcq4/websocket' that failed.

![Image](https://github.com/user-attachments/assets/f43ee387-e697-4f0b-97cc-6af4dceddd99)

**Comment by raza2022** [comment]
@Ellie-dynamsoft Thanks for the input and yes the driver is installed on Mac, but yes I didn't notice the scanner (sources) part initially, one more detail I got is he is using a Wi-Fi scanner so I am also checking this thing in detail, but thanks again as the issue is now narrowed down to only correct device detection point `sources` point will keep updating you once solved 👍

**Comment by raza2022** [comment]
hmm I see this part in docs and added all the sources in the list, let's see how it goes on client MAC, just attaching that part as an image for future users' reference (will close the issue once testing is done on the client machine)
![image](https://github.com/user-attachments/assets/c9ed02a2-c8fb-40a8-bb35-8ed5d925d0a0)

**Comment by raza2022** [comment]
Although the scanner connected with wifi is not detected, but when changed to USB it's working fine so I believe that's something different and the original issue resolved by adding `Dynamsoft.DWT.EnumDWT_DeviceType.ICASCANNER.` :100:
