### ISSUE TITLE
Get UUID id per device

### ISSUE THREAD

**Issue by OliviaAk** [Dynamsoft/Dynamic-Web-TWAIN#38]
I am using the Dynamsoft WEB TWAIN tool in the App, use license per client.
 And on the app side we need to track and save the generated UUID id after first installation.
Does Dynamsoft WEB TWAIN  support getting it from a DWT instance? 
Also there's an option to send message to the ws port, that SDK Dynamsoft used. But payload is required some  unique id, and then how get this id from app and instance ?
wss://127.0.0.1:18623/
method":"VersionInfo" 

Also notices that DWT.Load() event trigger request to the ws port, maybe we can get that response somehow

use: Nextjs+React

Thanks in advanced

**Comment by Ellie-dynamsoft** [comment]
"But the payload requires a unique id" You can enter any value for this unique id.

For example:

```javascript
await(await fetch('http://127.0.0.1:18622/fa/versionInfo', {
	method: 'post',
	body: JSON.stringify({
		id: '' + new Date().getTime(),
		method: "VersionInfo",
		version: "dwt_18000000"
	})
})).json()
```
The response you get will contain the UUID ID you need.

**Comment by OliviaAk** [comment]
Thanks a lot! That works for us!
