### ISSUE TITLE
GetWebTwain returns null if Load isn't used before

### ISSUE THREAD

**Issue by occult** [Dynamsoft/Dynamic-Web-TWAIN#6]
If I use the code example on your site such as 

```
handleClick() {

    Dynamsoft.WebTwainEnv.ProductKey="BB5378854D6D60CF72FD5D6EB92FB925A9204E14C7E80A7E504E707255412B0E90042463C14F5EB3BF4060D7ABE5ED65F60419A097E8B9DF29DE644BB84E68AC6720F03518D5B8AE794DE04BB0E22FB5ABB2982DDA0E2D9CB0236A286977A11762C537F9CBC6F4F707C60E92";

    var dwObject = Dynamsoft.WebTwainEnv.GetWebTwain('dwtcontrolContainer');

    var bSelected = dwObject.SelectSource();

    if (bSelected) {

      var onAcquireImageSuccess = function() { dwObject.CloseSource(); };

      var onAcquireImageFailure = onAcquireImageSuccess;

      dwObject.OpenSource();

      dwObject.AcquireImage({}, onAcquireImageSuccess, onAcquireImageFailure);

    }

  }
``` 

`dwObject` will return `null`. However, if I run `Dynamsoft.WebTwainEnv.Load();` before clicking on the button, it will work. 

I found the `Dynamsoft.WebTwainEnv.Load();` on [another website ](https://www.codeproject.com/Articles/5165717/Dynamic-Web-TWAIN-Programming-for-Angular-React-2) and have only seen it once in the documentation. 

Why doesn't the official documentation include the load? or am I missing something?

Thank you so much!! Besides that, this SDK is excellent.

**Comment by yushulx** [comment]
@occult thanks for your feedback. Can you provide the web page in which you found the code? 

I've looked up the issue. Please check out my comments.

### When should you use `Dynamsoft.WebTwainEnv.Load();`?

If `Dynamsoft.WebTwainEnv.AutoLoad = false;`, you need to manually load the TWAIN component.

```JS
Dynamsoft.WebTwainEnv.Load()
```

### The default AutoLoad property value 

If you install Dynamic Web TWAIN locally, you will get the resource folder.

![Annotation 2019-12-06 075946](https://user-images.githubusercontent.com/2202306/70284497-2a2e5400-17ff-11ea-934f-d319639ff4ee.png)

In `dynamsoft.webtwain.config.js`, you can see  `Dynamsoft.WebTwainEnv.AutoLoad = true;`. 

![Annotation 2019-12-06 081816](https://user-images.githubusercontent.com/2202306/70285003-0409b380-1801-11ea-8a5b-f85622ebb9c3.png)

In our official documentation, the SDK is used as follows:

```html
<head>
    <script type="text/javascript" src="Resources/dynamsoft.webtwain.initiate.js"></script>
    <script type="text/javascript" src="Resources/dynamsoft.webtwain.config.js"></script>
</head>
```

Alternatively, you can import the online JS source if you don't want to download the installer:

```html
<head>
    <script type="text/javascript" src="https://unpkg.com/dwt/dist/dynamsoft.webtwain.min.js"> </script>
</head>
```

Open the JS file to check the `AutoLoad` status:

![Annotation 2019-12-06 081200](https://user-images.githubusercontent.com/2202306/70284972-e9cfd580-1800-11ea-9098-45f74748e7d0.png)

The value is `false`.

Currently, I don't know why they are different. I'll confirm the issue with our R&D team.

**Comment by occult** [comment]
Thank you so much! You’re correct. I had this setting, but I thought it was for something else.


________________________________
