### ISSUE TITLE
DWObject.IfFeederEnabled

### ISSUE THREAD

**Issue by wahmedswl** [Dynamsoft/Dynamic-Web-TWAIN#7]
Hi, not able to set this option as after setting this value it reset it again to Empty or false value. This happening in MacOS.

Thanks

**Comment by Tom-Dynamsoft** [comment]
Thanks for reporting the issue. Please [collect logs](https://www.dynamsoft.com/web-twain/docs/indepth/troubleshooting/debug.html#enable-and-collect-verbose-logs) and share it with [support@dynamsoft.com](mailto:support@dynamsoft.com)
