### ISSUE TITLE
Unable to Scan Image from mock scanner

### ISSUE THREAD

**Issue by harivenkatesh-id** [Dynamsoft/Dynamic-Web-TWAIN#8]
Hi,

I'm using16.2.4 version of DWT in my Angular11 web application. I have imported 

import Dynamsoft from 'dwt';
import { WebTwainAcquire } from 'dwt/dist/types/WebTwain.Acquire'; in my scan-document.ts file

my ngOninit() looks like 

    this.DWObject = Dynamsoft.WebTwainEnv.GetWebTwain(this.containerId);
    Dynamsoft.WebTwainEnv.AutoLoad = true;
    Dynamsoft.WebTwainEnv.Containers = [{ WebTwainId: 'dwtObject', ContainerId: this.containerId, Width: '637px', Height: '515px'}];
    Dynamsoft.WebTwainEnv.RegisterEvent('OnWebTwainReady', () => { this.Dynamsoft_OnReady() });
    Dynamsoft.WebTwainEnv.ProductKey = "myLicenseKey";
    Dynamsoft.WebTwainEnv.ResourcesPath = 'Resources';
    Dynamsoft.WebTwainEnv.Load();

When i click on scan it will call acquireImage() method which looks like below

      let _this = this;
      if(!this.DWObject)
      this.DWObject = Dynamsoft.WebTwainEnv.GetWebTwain(this.containerId);
      if(this.DWObject.SourceCount > 0 && this.DWObject.SelectSourceByIndex(this.selectSources.selectedIndex)) {
      let onAcquireImageSuccess = () => {
        _this.processScannedDocument(_this.DWObject);
        _this.DWObject.CloseSource();
      };

      let onAcquireImageFailure = (deviceConfiguration: any,errorCode: any,errorString: any) => {
        _this.DWObject.CloseSource();
      }
      this.DWObject.OpenSource();
      this.DWObject.AcquireImage({}, onAcquireImageSuccess, onAcquireImageFailure)
      } else {
       alert("No source Available");
      }

**ISSUE:** After calling method this.DWObject.AcquireImage(), DWT keeps showing loading icon, its not going into either success method nor failure method.

Is my approach correct ?

**Comment by Tom-Dynamsoft** [comment]
The code seems to be OK. Any chance to test a different scanner?

If you are testing on Windows, you can try this virtual scanner
https://www.dynamsoft.com/download/TWAIN/twainds.win32.installer.2.1.3.msi

**Comment by harivenkatesh-id** [comment]
This was due to proxy issue from our side.
