### ISSUE TITLE
I not get dynamsoft ResourcesPath from floder nuxt js

### ISSUE THREAD

**Issue by b23618** [Dynamsoft/Dynamic-Web-TWAIN#9]
Packege.json

```
"scripts": {
  "dev": "ncp node_modules/dwt/dist static/dwt-resources && nuxt",
  "build": "nuxt build",
  "start": "nuxt start",
  "generate": "nuxt generate && ncp node_modules/dwt/dist dist/dwt-resources"
}
```

I use nuxt js framwork, How to want call floder dwt-resources from static floder ?

**Comment by lincoln2018** [comment]
"scripts": {
  "dev": "ncp node_modules/dwt/dist static/dwt-resources && nuxt",
  "build": "nuxt build",
  "start": "nuxt start",
  "generate": "nuxt generate && ncp node_modules/dwt/dist **static**/dwt-resources"
}

Ref url: [https://nuxtjs.org/docs/2.x/directory-structure/static/](https://nuxtjs.org/docs/2.x/directory-structure/static/)

The **static directory** is directly mapped to the server **root** and contains files that likely won't be changed. All included files will be automatically served by Nuxt and are accessible through your project root URL.

/static/robots.txt will be available at http://localhost:3000/robots.txt
